plugins {
    id 'com.android.library'
    id 'kotlin-android'
    id 'maven-publish'
}
ext {
    publishVersion = '1.0.4-SNAPSHOT'
    publishArtifactName = 'UICompose'
    publishComponentType = 'aar-release'
}
apply from:'../../publish-tool.gradle'

android {
    compileSdk rootProject.ext.compileSdk

    defaultConfig {
        minSdk rootProject.ext.minSdk
        targetSdk rootProject.ext.targetSdk
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
}

dependencies {

    implementation rootProject.ext.appcompat
    implementation rootProject.ext.recyclerview
    implementation rootProject.ext.constraintlayout
    implementation rootProject.ext.material
    implementation rootProject.ext.viewpager2

    implementation rootProject.ext.core_ktx

    testImplementation 'junit:junit:4.+'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
}