plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
    id 'maven-publish'
    id 'kotlin-kapt'
}

ext {
    publishVersion = '1.1.1-SNAPSHOT'
    publishArtifactName = 'AppLogcat'
    publishComponentType = 'aar-release'
}
apply from:'../../publish-tool.gradle'

android {
    compileSdk rootProject.ext.compileSdk

    defaultConfig {
        minSdk rootProject.ext.minSdk
        targetSdk rootProject.ext.targetSdk

        consumerProguardFiles "consumer-rules.pro"
        externalNativeBuild {
            cmake {
                abiFilters 'armeabi-v7a', 'arm64-v8a'
                cppFlags ''

            }
        }

    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'

        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }

    dataBinding { // 开启 DataBinding
        enabled true
    }

    buildFeatures {
        prefab true
    }
    externalNativeBuild {
        cmake {
            path "src/main/cpp/CMakeLists.txt"
            version '3.18.1'

        }
    }
    packagingOptions {
        exclude '**/libbytehook.so'
    }

}

dependencies {

    implementation rootProject.ext.appcompat
    implementation rootProject.ext.recyclerview
    implementation rootProject.ext.constraintlayout

    implementation rootProject.ext.core_ktx

    compileOnly rootProject.ext.timber

    kapt rootProject.ext.databinding_compiler // DataBinding 注解处理依赖

    def room_version = "2.4.3"
    implementation "androidx.room:room-runtime:$room_version"
    kapt "androidx.room:room-compiler:$room_version"
    // Room的Kotlin扩展和对协程的支持
    implementation "androidx.room:room-ktx:$room_version"

    implementation 'com.bytedance:bytehook:1.0.7'


}