package com.lazylite.annotationlib;

public class Constants {

    /**
     * init
     * */
    public static final String ANNOTATION_FULL_NAME = "com.lazylite.annotationlib.AutoInit";

    public static final String PACKAGE = "com.lazy.lite.auto";

    public static final String CLASS_NAME = "InitImpl";

    /**
     * deeplink
     * */
    public static final String ANNOTATION_DEEP_LINK_FULL_NAME = "com.lazylite.annotationlib.DeepLink";

    public static final String DEEP_LINK_PACKAGE = "com.lazy.lite.auto";

    public static final String DEEP_LINK_CLASS_NAME = "DeepLinkImpl";



    public static final String SEPARATOR = "$";

    public static final String WARNING_TIPS = "generated by apt don't edit!";

}
